---
- name: Install Epel repository
  yum:
    name: epel-release
    state: present

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Centos -- Install pip
  yum:
    name: python-pip
    state: present

- name: Add Docker repository.
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Centos -- Install docker-ce
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - net-tools
