---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-1
    image: geerlingguy/docker-centos7-ansible
    privileged: True
    required: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /usr/lib/systemd/systemd
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: centos7
verifier:
  name: testinfra
  lint:
    name: flake8
